name = "pesde/moonwave_extractor"
version = "1.2.1"
description = "Moonwave is a tool for generating documentation from comments in Lua source code."
authors = ["eryn L. K. <https://eryn.io/>"]
repository = "https://github.com/pesde-pkg/tooling/tree/main/bins/moonwave-extractor"
includes = ["init.luau", "README.md", "pesde.toml"]

[target]
environment = "lune"
bin = "init.luau"

[dependencies]
result = { name = "lukadev_0/result", version = "^1.2.0" }
option = { name = "lukadev_0/option", version = "^1.2.0" }
core = { workspace = "pesde/toolchainlib", version = "^" }

[indices]
default = "https://github.com/pesde-pkg/index"
